name = "edgerender"
type = "javascript"
zone_id = ""
account_id = "d6252a570c309c113744c9e11317e271"
route = ""
webpack_config = "webpack.config.js"
workers_dev = true
kv_namespaces = [
  { binding = "ASSETS", preview_id = "e0a7c29ebdc844cc8d70e0ed1275c851", id = "bccee624e44446c7bd42700f58361546" }
]

[site]
bucket = "./dist/assets"
entry-point = "."

[build]
command = "yarn build"
[build.upload]
format = "service-worker"
